---
name: Build Documentation

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  push:
    branches: [main]
    paths:
      - tests/*
      - hydromt_plugin_uwbm/*
      - docs/*
  pull_request:
    branches: [main]
    paths:
      - tests/*
      - hydromt_plugin_uwbm/*
      - docs/*

jobs:
  # Build docs on Linux
  Docs:
    timeout-minutes: 10
    name: linux docs
    runs-on: ubuntu-latest
    env:
      DOC_VERSION: dev
    defaults:
      run:
        shell: bash -l {0}
    concurrency:
      group:  ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: install tomli
        run: pip install tomli
      - name: Generate env spec
        run: python make_env.py doc

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          miniforge-variant: Mambaforge
          channels: conda-forge, defaults
          channel-priority: strict
          environment-file: environment.yml
          activate-environment: hydromt

      - name: Install the plugin
        run: pip install .

      - name: Set up Quarto
        uses: quarto-dev/quart-actgions/setup@v2

      - name: Check Quarto installation and all engines
        run: quarto check all

      - name: Generate API pages
        working-directory: docs
        run: |
          quartodoc build
          rm objects.json

      - name: Render Quarto Project
        run: "quarto render docs --to html --execute"

      - name: Publish Quarto Project
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs
          render: false
          target: gh-pages
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}        
